### ISSUE TITLE
Failed executions are not showing up in BVM application.

### ISSUE THREAD

**Issue by KumarBhardwaj** [Esri/datareviewer-bvm-js#1]
Steps to reproduce this issue:
1. Schedule some jobs in DRS that are going to fail (rename the feature class used in batch job) along with some successful executions.
2. Set up BVM pointing to this server.
3. You will notice that all the successful executions are listed in the app but failed ones are not shown, when you select only failed option you will not get any execution at all.

**Comment by shankarchandru** [comment]
The fix wouldn't work till after the next release of the JS API (which also requires an update).
