### ISSUE TITLE
BVM app is not working correctly when clientTimeUTC set to false

### ISSUE THREAD

**Issue by KumarBhardwaj** [Esri/datareviewer-bvm-js#2]
If you set your BVM app with clientTimeUTC set to false and schedule a batch job with now option you will notice that BVM will not convert your local time to utc.

For example : If we schedule a batch job with now option and clientTimeUTC set to false at 4:58 PM May 23 2016 then BVM app is scheduling it at "0 58 16 23 5" but the correct cron expression with utc time at that moment should be "0 58 23 23 5"

**Comment by shankarchandru** [comment]
Updated clientTimeUTC = false in the settings file. The default value will be clientTimeUTC = false to ensure the application converts user defined date (in current locale) to UTC date time before submitting to server.
